version: "3.3"

services:

  db:
    restart: always
    container_name: todo_db
    image: postgres:latest
    env_file:
      - ./.env
    expose:
      - "5432"
    command: -p 5432
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB_NAME}

  web:
    build: .
    env_file:
      - ./.env
    command:
      - sh
      - -c
      - |
        python3 main.py
        pytest tests/
    volumes:
      - .:/code
    ports:
      - "8003:8003"
    depends_on:
      - db
    container_name: todo_backend

  test_db:
    restart: always
    container_name: todo_db_test
    image: postgres:latest
    env_file:
      - ./.env
    expose:
      - "5433"
    command: -p 5433
    ports:
      - "5433:5433"
    volumes:
      - ./postgres-data-test:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_TEST}
      POSTGRES_USER: ${POSTGRES_USER_TEST}
      POSTGRES_DB: ${POSTGRES_DB_NAME_TEST}
