name: Android Build

on:
  push:
    branches:
      - master
    paths:
      - Taskly/**
      - .github/workflows/android.yml

jobs:
  Gradle:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: setup jdk
      uses: actions/setup-java@v3
      with:
        java-version: 1.8
        distribution: 'temurin'
    - name: Make Gradle executable
      run: chmod +x ./gradlew
      working-directory: ./Taskly
    - name: Build Release APK
      run: ./gradlew assembleRelease
      working-directory: ./Taskly
    - name: Releasing using Hub
      uses: kyze8439690/action-release-releaseapk@master
      env:
       GITHUB_TOKEN: ${{ secrets.TOKEN }}
       APP_FOLDER: app
